version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  EmsApiTestEndpoint: https://emsapibeta.ausdig.com/api
  EmsApiTestUsername:
    secure: IpC7n4Gq5x7QPNSkY4FNrw==
  EmsApiTestPassword:
    secure: qTDOVAxHa2DdMrpU276vMQ==
nuget:
  project_feed: true
build_script:
- ps: '& .\csharp\EmsApi.Dto\Update-EmsApiSwaggerSpecAuto.ps1; & .\csharp\build.ps1 -Release'
test:
  assemblies: csharp\bin\EmsApi.Client.Tests.dll
artifacts:
- path: csharp\bin\EmsApi.Client.*.nupkg
  name: Release
- path: csharp\bin\EmsApi.Client.dll
  name: Release
- path: csharp\bin\EmsApi.Dto.dll
  name: Release